version: '3'

services:
  chemocobra:
    build: ./
    image: chemocobra
    # env_file: 
    #   - ../../web.env
    user: ${CURRENT_UID}
    volumes:
      - ../:/code/
    ports:
      - "8200:8000"
    working_dir: /code/
    command: > 
      bash -c "python manage.py collectstatic --noinput
      && python manage.py runmodwsgi --processes=1 --threads=5"